# <img src="https://raw.githubusercontent.com/iterative/datachain/main/docs/assets/datachain.svg" style="height: 32px; width: 32px; vertical-align: bottom"/> Tutorial: Working with Video Datasets

This tutorial dives into techniques to manage video datasets datasets.

**📋 Topics covered:**
1. Building a Video DataChain for [AVA Actions](https://research.google.com/ava/) video dataset
2. Creating a Data Model for YOLOv11 Pose Detection projects
3. Integrating Video-Level Annotations from CSV
5. Extract and Manage Video Frames
6. Running Pose Detection with YOLOv11 and Saving to DataChain
7. Visualizing Pose Data

## Setup

To start, install the dependencies.

In [1]:
%pip install -q 'datachain[video]'

Note: you may need to restart the kernel to use updated packages.

## Get data and create DataChain

We will use **AVA Actions dataset** from [https://research.google.com/ava/download.html](https://research.google.com/ava/download.html#ava_actions_download). To download dataset, use the following script:

In [2]:
%%bash

# Download video files list
DATA_DIR="data/ava"
mkdir -p ${DATA_DIR}

wget -q https://s3.amazonaws.com/ava-dataset/annotations/ava_file_names_trainval_v2.1.txt -O ${DATA_DIR}/ava_file_names_trainval_v2.1.txt

# Download video files
VIDEOS_DIR="${DATA_DIR}/videos"
mkdir -p ${VIDEOS_DIR}

for file in $(cat ${DATA_DIR}/ava_file_names_trainval_v2.1.txt | head -3); do
    echo -n "Download '${file}'... "
    if [[ ! -f ${VIDEOS_DIR}/${file} ]]; then
        wget -q https://s3.amazonaws.com/ava-dataset/trainval/${file} -P ${VIDEOS_DIR}
    fi
    echo "OK"
done

# Download annotations
ANNOTATIONS_DIR="${DATA_DIR}/annotations"
mkdir -p ${ANNOTATIONS_DIR}

wget -q https://research.google.com/ava/download/ava_v2.2.zip -O ${DATA_DIR}/ava_v2.2.zip
unzip -qo ${DATA_DIR}/ava_v2.2.zip -d ${ANNOTATIONS_DIR}

# Prepare output directory for video clips
mkdir -p ${DATA_DIR}/clips

Download '_-Z6wFjXtGQ.mkv'... OK
Download '_145Aa_xkuE.mp4'... OK
Download '_7oWZq_s_Sk.mkv'... OK

### Indexing storage

To create a chain from a directory of files, use `DataChain.from_storage()` and point to the location of the directory:

In [3]:
from datachain import DataChain

repo_dc = DataChain.from_storage("./data/ava/videos", type="video", update=True)

Processed: 0 rows [00:00, ? rows/s]
ting file:///Users/vlad/work/iterative/datachain-examples/video/data/ava/videos: 0 objects [00:00, ? objects/s]

Preview created chain:

In [4]:
repo_dc.show(10)

,file,file,file,file,file,file,file,file
,source,path,size,version,etag,is_latest,last_modified,location
0,file:///Users/vlad/work/iterative/datachain-ex...,9Y_l9NsnYE0.mp4,299051037,,0x1.6a6d311c00000p+30,1,2018-03-04 01:30:47+00:00,None
1,file:///Users/vlad/work/iterative/datachain-ex...,G4qq1MRXCiY.mkv,204727729,,0x1.6a6eceec00000p+30,1,2018-03-04 08:52:11+00:00,None
2,file:///Users/vlad/work/iterative/datachain-ex...,4gVsDd8PV9U.mp4,587579944,,0x1.6a6c6bb400000p+30,1,2018-03-03 22:00:13+00:00,None
3,file:///Users/vlad/work/iterative/datachain-ex...,c9pEMjPT16M.webm,340432181,,0x1.6a6de73000000p+30,1,2018-03-04 04:45:00+00:00,None
4,file:///Users/vlad/work/iterative/datachain-ex...,Gt61_Yekkgc.mp4,326660841,,0x1.6a6f0d3400000p+30,1,2018-03-04 09:58:37+00:00,None
5,file:///Users/vlad/work/iterative/datachain-ex...,-IELREHX_js.mp4,125710755,,0x1.6a6c20ec00000p+30,1,2018-03-03 20:40:27+00:00,None
6,file:///Users/vlad/work/iterative/datachain-ex...,0wBYFahr3uI.mp4,274752600,,0x1.6a6c317c00000p+30,1,2018-03-03 20:58:07+00:00,None
7,file:///Users/vlad/work/iterative/datachain-ex...,bePts02nIY8.mkv,272741181,,0x1.6a6dcdc400000p+30,1,2018-03-04 04:17:53+00:00,None
8,file:///Users/vlad/work/iterative/datachain-ex...,bSZiZ4rOC7c.mkv,220409224,,0x1.6a6dd5d000000p+30,1,2018-03-04 04:26:28+00:00,None
9,file:///Users/vlad/work/iterative/datachain-ex...,2E_e8JlvTlg.mkv,482575843,,0x1.6a6c434400000p+30,1,2018-03-03 21:17:05+00:00,None

[Limited by 10 rows]

DataChain created a record for each file in the repository, generating a `file` signal for each file. The file signal contains subsignals with metadata about each file, like `file.name` and `file.size`. By default all `file` signals will have `File` type, by using `type="video"` param we can specify type of the files to `VideoFile`.

### Adding YouTube video ID

We will need YouTube video ID to process files. Let's create mapper to add `video_id` signal:

In [5]:
from datachain import File

def video_id(file: File) -> str:
    return file.path[:11]

repo_dc2 = repo_dc.map(video_id, output=['video_id']).save()

Preview created chain:

In [6]:
repo_dc2.show(10)

,file,file,file,file,file,file,file,file,video_id
,source,path,size,version,etag,is_latest,last_modified,location,
0,file:///Users/vlad/work/iterative/datachain-ex...,9Y_l9NsnYE0.mp4,299051037,,0x1.6a6d311c00000p+30,1,2018-03-04 01:30:47+00:00,None,9Y_l9NsnYE0
1,file:///Users/vlad/work/iterative/datachain-ex...,G4qq1MRXCiY.mkv,204727729,,0x1.6a6eceec00000p+30,1,2018-03-04 08:52:11+00:00,None,G4qq1MRXCiY
2,file:///Users/vlad/work/iterative/datachain-ex...,4gVsDd8PV9U.mp4,587579944,,0x1.6a6c6bb400000p+30,1,2018-03-03 22:00:13+00:00,None,4gVsDd8PV9U
3,file:///Users/vlad/work/iterative/datachain-ex...,c9pEMjPT16M.webm,340432181,,0x1.6a6de73000000p+30,1,2018-03-04 04:45:00+00:00,None,c9pEMjPT16M
4,file:///Users/vlad/work/iterative/datachain-ex...,Gt61_Yekkgc.mp4,326660841,,0x1.6a6f0d3400000p+30,1,2018-03-04 09:58:37+00:00,None,Gt61_Yekkgc
5,file:///Users/vlad/work/iterative/datachain-ex...,-IELREHX_js.mp4,125710755,,0x1.6a6c20ec00000p+30,1,2018-03-03 20:40:27+00:00,None,-IELREHX_js
6,file:///Users/vlad/work/iterative/datachain-ex...,0wBYFahr3uI.mp4,274752600,,0x1.6a6c317c00000p+30,1,2018-03-03 20:58:07+00:00,None,0wBYFahr3uI
7,file:///Users/vlad/work/iterative/datachain-ex...,bePts02nIY8.mkv,272741181,,0x1.6a6dcdc400000p+30,1,2018-03-04 04:17:53+00:00,None,bePts02nIY8
8,file:///Users/vlad/work/iterative/datachain-ex...,bSZiZ4rOC7c.mkv,220409224,,0x1.6a6dd5d000000p+30,1,2018-03-04 04:26:28+00:00,None,bSZiZ4rOC7c
9,file:///Users/vlad/work/iterative/datachain-ex...,2E_e8JlvTlg.mkv,482575843,,0x1.6a6c434400000p+30,1,2018-03-03 21:17:05+00:00,None,2E_e8JlvTlg

[Limited by 10 rows]

### Create annotations DataChain

Each row in annotations CSV file contains an annotation for one person performing an action in an interval, where that annotation is associated with the middle frame. Different persons and multiple action labels are described in separate rows.

The format of a row is the following: `video_id`, `middle_frame_timestamp`, `person_box`, `action_id`, `person_id`

- `video_id`: YouTube identifier
- `middle_frame_timestamp`: in seconds from the start of the YouTube.
- `person_box`: top-left (x1, y1) and bottom-right (x2,y2) normalized with respect to frame size, where (0.0, 0.0) corresponds to the top left, and (1.0, 1.0) corresponds to bottom right.
- `action_id`: identifier of an action class, see ava_action_list_v2.2.pbtxt
- `person_id`: a unique integer allowing this box to be linked to other boxes depicting the same person in adjacent frames of this video.

In [7]:
from datachain import DataChain, DataModel

class AvaMeta(DataModel):
    video_id: str
    timestamp: int
    box_left: float
    box_top: float
    box_right: float
    box_bottom: float
    action_id: int
    person_id: int

annotations_dc = DataChain.from_csv(
    "./data/ava/annotations/ava_train_v2.2.csv",
    output=AvaMeta,
    source=False,
    settings={'prefetch': 0, 'cache': False},
).save()

Processed: 0 rows [00:00, ? rows/s]

Processed: 0 rows [00:00, ? rows/s]

Processed: 0 rows [00:00, ? rows/s]
sed by pyarrow: 0rows [00:00, ?rows/s]

ted: 0 rows [00:00, ? rows/s]
sed by pyarrow: 4090rows [00:00, 40899.16rows/s]

ted: 7767 rows [00:00, 77666.19 rows/s]
sed by pyarrow: 10633rows [00:00, 55326.73rows/s]

ted: 15534 rows [00:00, 71226.71 rows/s]
sed by pyarrow: 18324rows [00:00, 65181.23rows/s]

ted: 22692 rows [00:00, 60515.56 rows/s]
sed by pyarrow: 24843rows [00:00, 57972.67rows/s]

ted: 30001 rows [00:00, 62741.78 rows/s]
sed by pyarrow: 31414rows [00:00, 60554.99rows/s]

ted: 37982 rows [00:00, 68253.97 rows/s]
sed by pyarrow: 39374rows [00:00, 66704.92rows/s]

ted: 44942 rows [00:00, 51543.36 rows/s]
sed by pyarrow: 46135rows [00:00, 50569.17rows/s]

ted: 50688 rows [00:00, 52235.13 rows/s]
sed by pyarrow: 51775rows [00:00, 51416.30rows/s]

ted: 58636 rows [00:00, 59384.67 rows/s]
sed by pyarrow: 59725rows [00:01, 58825.89rows/s]

ted: 65158 rows [00:01, 60974.61 rows/s]
sed by pyarrow: 66030rows [00:01, 55399.41rows/s]

ted: 71578 rows [00:01, 57102.96 rows/s]
sed by pyarrow: 72673rows [00:01, 58326.30rows/s]

ted: 79232 rows [00:01, 62346.30 rows/s]
sed by pyarrow: 80000rows [00:01, 59628.70rows/s]

ted: 85714 rows [00:01, 62255.13 rows/s]
sed by pyarrow: 87820rows [00:01, 64692.18rows/s]

ted: 92111 rows [00:01, 57573.74 rows/s]
sed by pyarrow: 94472rows [00:01, 59422.91rows/s]

ted: 100001 rows [00:01, 61001.51 rows/s]
sed by pyarrow: 101272rows [00:01, 61716.53rows/s]

ted: 108154 rows [00:01, 66558.24 rows/s]
sed by pyarrow: 109459rows [00:01, 67286.67rows/s]

ted: 114961 rows [00:01, 59539.01 rows/s]
sed by pyarrow: 116352rows [00:01, 59965.98rows/s]

ted: 122046 rows [00:02, 62495.60 rows/s]
sed by pyarrow: 123394rows [00:02, 62721.26rows/s]

ted: 130001 rows [00:02, 65093.17 rows/s]
sed by pyarrow: 130417rows [00:02, 64774.92rows/s]

ted: 136654 rows [00:02, 62502.68 rows/s]
sed by pyarrow: 137062rows [00:02, 62164.55rows/s]

ted: 143346 rows [00:02, 63701.97 rows/s]
sed by pyarrow: 143748rows [00:02, 63461.45rows/s]

ted: 150001 rows [00:02, 64120.79 rows/s]
sed by pyarrow: 150232rows [00:02, 63851.17rows/s]

ted: 156477 rows [00:02, 61602.01 rows/s]
sed by pyarrow: 156691rows [00:02, 61406.18rows/s]

ted: 163164 rows [00:02, 63076.54 rows/s]
sed by pyarrow: 163387rows [00:02, 62976.10rows/s]
sed by pyarrow: 170000rows [00:02, 60309.46rows/s]

ted: 170001 rows [00:02, 60387.27 rows/s]

ted: 176103 rows [00:02, 58671.76 rows/s]
sed by pyarrow: 176103rows [00:02, 58411.05rows/s]

ted: 182627 rows [00:02, 60486.70 rows/s]
sed by pyarrow: 182628rows [00:03, 60310.87rows/s]
sed by pyarrow: 190000rows [00:03, 62748.96rows/s]

ted: 190001 rows [00:03, 62643.94 rows/s]
sed by pyarrow: 197582rows [00:03, 66467.00rows/s]

ted: 197583 rows [00:03, 66369.53 rows/s]

ted: 204264 rows [00:03, 61032.08 rows/s]
sed by pyarrow: 204272rows [00:03, 60886.73rows/s]

ted: 211116 rows [00:03, 63082.34 rows/s]
sed by pyarrow: 211122rows [00:03, 62971.54rows/s]

ted: 219124 rows [00:03, 67861.71 rows/s]
sed by pyarrow: 219129rows [00:03, 67780.72rows/s]

ted: 226006 rows [00:03, 62405.35 rows/s]
sed by pyarrow: 226007rows [00:03, 62343.32rows/s]
sed by pyarrow: 232385rows [00:03, 61842.67rows/s]

ted: 232387 rows [00:03, 61689.56 rows/s]
sed by pyarrow: 240000rows [00:03, 64340.93rows/s]

ted: 240001 rows [00:03, 64218.59 rows/s]

ted: 246496 rows [00:03, 61999.35 rows/s]
sed by pyarrow: 246508rows [00:04, 61887.21rows/s]

ted: 253528 rows [00:04, 64303.37 rows/s]
sed by pyarrow: 253546rows [00:04, 64236.89rows/s]

ted: 260574 rows [00:04, 66049.37 rows/s]
sed by pyarrow: 260595rows [00:04, 66008.30rows/s]

ted: 267230 rows [00:04, 63549.10 rows/s]
sed by pyarrow: 267249rows [00:04, 63514.57rows/s]

ted: 274137 rows [00:04, 65112.84 rows/s]
sed by pyarrow: 274155rows [00:04, 65084.22rows/s]

ted: 281068 rows [00:04, 66321.91 rows/s]
sed by pyarrow: 281083rows [00:04, 66292.67rows/s]

ted: 287736 rows [00:04, 63556.54 rows/s]
sed by pyarrow: 287749rows [00:04, 63538.05rows/s]

ted: 294136 rows [00:04, 61983.54 rows/s]
sed by pyarrow: 294147rows [00:04, 61969.10rows/s]

ted: 301131 rows [00:04, 64242.45 rows/s]
sed by pyarrow: 301140rows [00:04, 64225.62rows/s]

ted: 308023 rows [00:04, 62496.29 rows/s]
sed by pyarrow: 308023rows [00:04, 62482.88rows/s]

ted: 314691 rows [00:05, 63675.16 rows/s]
sed by pyarrow: 314695rows [00:05, 63676.37rows/s]

ted: 321648 rows [00:05, 65365.88 rows/s]
sed by pyarrow: 321653rows [00:05, 65370.24rows/s]

ted: 329854 rows [00:05, 70220.63 rows/s]
sed by pyarrow: 329859rows [00:05, 70223.86rows/s]

ted: 336913 rows [00:05, 64237.26 rows/s]
sed by pyarrow: 336919rows [00:05, 64236.99rows/s]

ted: 343901 rows [00:05, 65799.28 rows/s]
sed by pyarrow: 343907rows [00:05, 65798.70rows/s]

ted: 350577 rows [00:05, 64285.13 rows/s]
sed by pyarrow: 350583rows [00:05, 64293.99rows/s]

ted: 357074 rows [00:05, 54202.31 rows/s]
sed by pyarrow: 357081rows [00:05, 54187.25rows/s]

ted: 364017 rows [00:05, 58060.94 rows/s]
sed by pyarrow: 364029rows [00:05, 58060.29rows/s]

ted: 371090 rows [00:05, 61428.31 rows/s]
sed by pyarrow: 371108rows [00:06, 61442.16rows/s]

ted: 377470 rows [00:06, 60362.15 rows/s]
sed by pyarrow: 377491rows [00:06, 60367.04rows/s]

ted: 384561 rows [00:06, 63276.78 rows/s]
sed by pyarrow: 384586rows [00:06, 63291.29rows/s]

ted: 391699 rows [00:06, 65570.36 rows/s]
sed by pyarrow: 391725rows [00:06, 65582.42rows/s]

ted: 398368 rows [00:06, 63463.92 rows/s]
sed by pyarrow: 398396rows [00:06, 63466.05rows/s]

ted: 405400 rows [00:06, 65408.90 rows/s]
sed by pyarrow: 405430rows [00:06, 65415.84rows/s]

ted: 412014 rows [00:06, 62619.09 rows/s]
sed by pyarrow: 412045rows [00:06, 62616.79rows/s]

ted: 418345 rows [00:06, 61352.30 rows/s]
sed by pyarrow: 418376rows [00:06, 61355.89rows/s]

ted: 425219 rows [00:06, 63438.20 rows/s]
sed by pyarrow: 425248rows [00:06, 63436.15rows/s]

ted: 431879 rows [00:06, 64346.72 rows/s]
sed by pyarrow: 431890rows [00:06, 64290.71rows/s]

ted: 439978 rows [00:07, 63284.37 rows/s]
sed by pyarrow: 439978rows [00:07, 63274.08rows/s]

ted: 446879 rows [00:07, 64860.78 rows/s]
sed by pyarrow: 446879rows [00:07, 64812.79rows/s]

ted: 453771 rows [00:07, 66005.27 rows/s]
sed by pyarrow: 453780rows [00:07, 65994.88rows/s]

ted: 460769 rows [00:07, 67146.86 rows/s]
sed by pyarrow: 460793rows [00:07, 67183.36rows/s]

ted: 467515 rows [00:07, 64354.48 rows/s]
sed by pyarrow: 467542rows [00:07, 64343.88rows/s]

ted: 473991 rows [00:07, 62583.37 rows/s]
sed by pyarrow: 474018rows [00:07, 62602.45rows/s]

ted: 480922 rows [00:07, 64486.82 rows/s]
sed by pyarrow: 480956rows [00:07, 64520.07rows/s]

ted: 487405 rows [00:07, 62576.33 rows/s]
sed by pyarrow: 487442rows [00:07, 62598.27rows/s]

ted: 494340 rows [00:07, 64506.37 rows/s]
sed by pyarrow: 494377rows [00:07, 64521.39rows/s]

ted: 501374 rows [00:07, 66193.84 rows/s]
sed by pyarrow: 501412rows [00:08, 66206.60rows/s]

ted: 508022 rows [00:08, 63686.97 rows/s]
sed by pyarrow: 508061rows [00:08, 63696.90rows/s]

ted: 515101 rows [00:08, 65719.03 rows/s]
sed by pyarrow: 515140rows [00:08, 65727.98rows/s]

ted: 522186 rows [00:08, 67207.39 rows/s]
sed by pyarrow: 522218rows [00:08, 67194.21rows/s]

ted: 528936 rows [00:08, 64062.90 rows/s]
sed by pyarrow: 528967rows [00:08, 64035.04rows/s]

ted: 535389 rows [00:08, 62658.85 rows/s]
sed by pyarrow: 535418rows [00:08, 62647.82rows/s]

ted: 542136 rows [00:08, 64025.84 rows/s]
sed by pyarrow: 542163rows [00:08, 64013.25rows/s]

ted: 549877 rows [00:08, 63034.06 rows/s]
sed by pyarrow: 549877rows [00:08, 63020.52rows/s]

ted: 556741 rows [00:08, 64585.90 rows/s]
sed by pyarrow: 556745rows [00:08, 64587.40rows/s]

ted: 563586 rows [00:08, 65680.30 rows/s]
sed by pyarrow: 563586rows [00:08, 65662.15rows/s]

ted: 570518 rows [00:09, 66728.96 rows/s]
sed by pyarrow: 570528rows [00:09, 66745.52rows/s]

ted: 577218 rows [00:09, 64118.64 rows/s]
sed by pyarrow: 577229rows [00:09, 64124.41rows/s]

ted: 583665 rows [00:09, 55605.75 rows/s]
sed by pyarrow: 583677rows [00:09, 55590.57rows/s]
sed by pyarrow: 590000rows [00:09, 55949.05rows/s]

ted: 590001 rows [00:09, 55786.64 rows/s]

ted: 595726 rows [00:09, 55154.54 rows/s]
sed by pyarrow: 595743rows [00:09, 55097.78rows/s]

ted: 602153 rows [00:09, 57625.29 rows/s]
sed by pyarrow: 602178rows [00:09, 57602.18rows/s]

ted: 609988 rows [00:09, 63411.07 rows/s]
sed by pyarrow: 610000rows [00:09, 60600.13rows/s]
sed by pyarrow: 616117rows [00:09, 58916.87rows/s]

ted: 616438 rows [00:09, 58222.90 rows/s]
sed by pyarrow: 622862rows [00:10, 61275.62rows/s]

ted: 623205 rows [00:09, 60783.40 rows/s]
sed by pyarrow: 630000rows [00:10, 63283.03rows/s]

ted: 630001 rows [00:10, 62654.34 rows/s]

ted: 637820 rows [00:10, 61385.73 rows/s]
sed by pyarrow: 637820rows [00:10, 61603.66rows/s]

ted: 644545 rows [00:10, 62974.51 rows/s]
sed by pyarrow: 644546rows [00:10, 63135.95rows/s]
sed by pyarrow: 650911rows [00:10, 61019.12rows/s]

ted: 650922 rows [00:10, 60742.39 rows/s]
sed by pyarrow: 658725rows [00:10, 65772.93rows/s]

ted: 658727 rows [00:10, 65539.56 rows/s]

ted: 665363 rows [00:10, 60127.01 rows/s]
sed by pyarrow: 665368rows [00:10, 60098.22rows/s]

ted: 671997 rows [00:10, 61805.99 rows/s]
sed by pyarrow: 672001rows [00:10, 61778.79rows/s]
sed by pyarrow: 680000rows [00:10, 64349.37rows/s]

ted: 680001 rows [00:10, 64183.52 rows/s]

ted: 686490 rows [00:10, 61747.82 rows/s]
sed by pyarrow: 686505rows [00:11, 61684.88rows/s]

ted: 693320 rows [00:11, 63547.07 rows/s]
sed by pyarrow: 693336rows [00:11, 63499.59rows/s]

ted: 700237 rows [00:11, 65131.05 rows/s]
sed by pyarrow: 700256rows [00:11, 65102.91rows/s]

ted: 706799 rows [00:11, 62667.94 rows/s]
sed by pyarrow: 706817rows [00:11, 62652.79rows/s]

ted: 713112 rows [00:11, 61562.75 rows/s]
sed by pyarrow: 713130rows [00:11, 61547.82rows/s]
sed by pyarrow: 720000rows [00:11, 63555.44rows/s]

ted: 720001 rows [00:11, 63366.13 rows/s]

ted: 726368 rows [00:11, 61792.12 rows/s]
sed by pyarrow: 726390rows [00:11, 61733.31rows/s]

ted: 733247 rows [00:11, 63788.75 rows/s]
sed by pyarrow: 733270rows [00:11, 63747.36rows/s]

ted: 740120 rows [00:11, 65219.52 rows/s]
sed by pyarrow: 740144rows [00:11, 65190.41rows/s]

ted: 747837 rows [00:11, 63393.43 rows/s]
sed by pyarrow: 747837rows [00:11, 63361.25rows/s]

ted: 754664 rows [00:12, 64749.84 rows/s]
sed by pyarrow: 754665rows [00:12, 64728.26rows/s]

ted: 761179 rows [00:12, 56768.42 rows/s]
sed by pyarrow: 761179rows [00:12, 56749.68rows/s]

ted: 769272 rows [00:12, 63107.72 rows/s]
sed by pyarrow: 769273rows [00:12, 63094.25rows/s]

ted: 775804 rows [00:12, 57213.16 rows/s]
sed by pyarrow: 775804rows [00:12, 57204.25rows/s]

ted: 782714 rows [00:12, 60292.54 rows/s]
sed by pyarrow: 782716rows [00:12, 60292.17rows/s]
sed by pyarrow: 790000rows [00:12, 63205.45rows/s]

ted: 790001 rows [00:12, 63034.00 rows/s]

ted: 796476 rows [00:12, 61386.03 rows/s]
sed by pyarrow: 796496rows [00:12, 61345.42rows/s]

ted: 803257 rows [00:12, 63160.41 rows/s]
sed by pyarrow: 803270rows [00:12, 63108.96rows/s]

ted: 810197 rows [00:12, 64925.59 rows/s]
sed by pyarrow: 810221rows [00:12, 64917.08rows/s]

ted: 816770 rows [00:13, 62334.45 rows/s]
sed by pyarrow: 816796rows [00:13, 62321.26rows/s]

ted: 823639 rows [00:13, 64127.73 rows/s]
sed by pyarrow: 823670rows [00:13, 64131.65rows/s]

ted: 830113 rows [00:13, 62713.76 rows/s]
sed by pyarrow: 830146rows [00:13, 62722.58rows/s]

ted: 836430 rows [00:13, 60856.84 rows/s]
sed by pyarrow: 836465rows [00:13, 60834.08rows/s]

ted: 843265 rows [00:13, 62980.15 rows/s]
sed by pyarrow: 843314rows [00:13, 63000.86rows/s]

ted: 850040 rows [00:13, 64353.80 rows/s]
sed by pyarrow: 850076rows [00:13, 64330.09rows/s]

ted: 857814 rows [00:13, 67322.24 rows/s]
sed by pyarrow: 857814rows [00:13, 67306.30rows/s]

Preview:

In [8]:
annotations_dc.show(10)

,video_id,timestamp,box_left,box_top,box_right,box_bottom,action_id,person_id
0,-5KQ66BBWC4,902,0.077,0.151,0.283,0.811,9,1
1,-5KQ66BBWC4,902,0.226,0.032,0.366,0.497,12,0
2,-5KQ66BBWC4,902,0.226,0.032,0.366,0.497,17,0
3,-5KQ66BBWC4,902,0.226,0.032,0.366,0.497,80,0
4,-5KQ66BBWC4,902,0.332,0.194,0.481,0.891,80,2
5,-5KQ66BBWC4,902,0.332,0.194,0.481,0.891,9,2
6,-5KQ66BBWC4,902,0.505,0.105,0.653,0.780,9,3
7,-5KQ66BBWC4,902,0.626,0.146,0.805,0.818,9,5
8,-5KQ66BBWC4,902,0.805,0.222,0.997,1.000,80,4
9,-5KQ66BBWC4,902,0.805,0.222,0.997,1.000,9,4

[Limited by 10 rows]

Action classes:

In [9]:
actions = {
    1: {'name': 'bend/bow (at the waist)', 'cls': 'PERSON_MOVEMENT'},
    2: {'name': 'crawl', 'cls': 'PERSON_MOVEMENT'},
    3: {'name': 'crouch/kneel', 'cls': 'PERSON_MOVEMENT'},
    4: {'name': 'dance', 'cls': 'PERSON_MOVEMENT'},
    5: {'name': 'fall down', 'cls': 'PERSON_MOVEMENT'},
    6: {'name': 'get up', 'cls': 'PERSON_MOVEMENT'},
    7: {'name': 'jump/leap', 'cls': 'PERSON_MOVEMENT'},
    8: {'name': 'lie/sleep', 'cls': 'PERSON_MOVEMENT'},
    9: {'name': 'martial art', 'cls': 'PERSON_MOVEMENT'},
    10: {'name': 'run/jog', 'cls': 'PERSON_MOVEMENT'},
    11: {'name': 'sit', 'cls': 'PERSON_MOVEMENT'},
    12: {'name': 'stand', 'cls': 'PERSON_MOVEMENT'},
    13: {'name': 'swim', 'cls': 'PERSON_MOVEMENT'},
    14: {'name': 'walk', 'cls': 'PERSON_MOVEMENT'},
    15: {'name': 'answer phone', 'cls': 'OBJECT_MANIPULATION'},
    16: {'name': 'brush teeth', 'cls': 'OBJECT_MANIPULATION'},
    17: {'name': 'carry/hold (an object)', 'cls': 'OBJECT_MANIPULATION'},
    18: {'name': 'catch (an object)', 'cls': 'OBJECT_MANIPULATION'},
    19: {'name': 'chop', 'cls': 'OBJECT_MANIPULATION'},
    20: {'name': 'climb (e.g., a mountain)', 'cls': 'OBJECT_MANIPULATION'},
    21: {'name': 'clink glass', 'cls': 'OBJECT_MANIPULATION'},
    22: {'name': 'close (e.g., a door, a box)', 'cls': 'OBJECT_MANIPULATION'},
    23: {'name': 'cook', 'cls': 'OBJECT_MANIPULATION'},
    24: {'name': 'cut', 'cls': 'OBJECT_MANIPULATION'},
    25: {'name': 'dig', 'cls': 'OBJECT_MANIPULATION'},
    26: {'name': 'dress/put on clothing', 'cls': 'OBJECT_MANIPULATION'},
    27: {'name': 'drink', 'cls': 'OBJECT_MANIPULATION'},
    28: {'name': 'drive (e.g., a car, a truck)', 'cls': 'OBJECT_MANIPULATION'},
    29: {'name': 'eat', 'cls': 'OBJECT_MANIPULATION'},
    30: {'name': 'enter', 'cls': 'OBJECT_MANIPULATION'},
    31: {'name': 'exit', 'cls': 'OBJECT_MANIPULATION'},
    32: {'name': 'extract', 'cls': 'OBJECT_MANIPULATION'},
    33: {'name': 'fishing', 'cls': 'OBJECT_MANIPULATION'},
    34: {'name': 'hit (an object)', 'cls': 'OBJECT_MANIPULATION'},
    35: {'name': 'kick (an object)', 'cls': 'OBJECT_MANIPULATION'},
    36: {'name': 'lift/pick up', 'cls': 'OBJECT_MANIPULATION'},
    37: {'name': 'listen (e.g., to music)', 'cls': 'OBJECT_MANIPULATION'},
    38: {'name': 'open (e.g., a window, a car door)', 'cls': 'OBJECT_MANIPULATION'},
    39: {'name': 'paint', 'cls': 'OBJECT_MANIPULATION'},
    40: {'name': 'play board game', 'cls': 'OBJECT_MANIPULATION'},
    41: {'name': 'play musical instrument', 'cls': 'OBJECT_MANIPULATION'},
    42: {'name': 'play with pets', 'cls': 'OBJECT_MANIPULATION'},
    43: {'name': 'point to (an object)', 'cls': 'OBJECT_MANIPULATION'},
    44: {'name': 'press', 'cls': 'OBJECT_MANIPULATION'},
    45: {'name': 'pull (an object)', 'cls': 'OBJECT_MANIPULATION'},
    46: {'name': 'push (an object)', 'cls': 'OBJECT_MANIPULATION'},
    47: {'name': 'put down', 'cls': 'OBJECT_MANIPULATION'},
    48: {'name': 'read', 'cls': 'OBJECT_MANIPULATION'},
    49: {'name': 'ride (e.g., a bike, a car, a horse)', 'cls': 'OBJECT_MANIPULATION'},
    50: {'name': 'row boat', 'cls': 'OBJECT_MANIPULATION'},
    51: {'name': 'sail boat', 'cls': 'OBJECT_MANIPULATION'},
    52: {'name': 'shoot', 'cls': 'OBJECT_MANIPULATION'},
    53: {'name': 'shovel', 'cls': 'OBJECT_MANIPULATION'},
    54: {'name': 'smoke', 'cls': 'OBJECT_MANIPULATION'},
    55: {'name': 'stir', 'cls': 'OBJECT_MANIPULATION'},
    56: {'name': 'take a photo', 'cls': 'OBJECT_MANIPULATION'},
    57: {'name': 'text on/look at a cellphone', 'cls': 'OBJECT_MANIPULATION'},
    58: {'name': 'throw', 'cls': 'OBJECT_MANIPULATION'},
    59: {'name': 'touch (an object)', 'cls': 'OBJECT_MANIPULATION'},
    60: {'name': 'turn (e.g., a screwdriver)', 'cls': 'OBJECT_MANIPULATION'},
    61: {'name': 'watch (e.g., TV)', 'cls': 'OBJECT_MANIPULATION'},
    62: {'name': 'work on a computer', 'cls': 'OBJECT_MANIPULATION'},
    63: {'name': 'write', 'cls': 'OBJECT_MANIPULATION'},
    64: {'name': 'fight/hit (a person)', 'cls': 'PERSON_INTERACTION'},
    65: {'name': 'give/serve (an object) to (a person)', 'cls': 'PERSON_INTERACTION'},
    66: {'name': 'grab (a person)', 'cls': 'PERSON_INTERACTION'},
    67: {'name': 'hand clap', 'cls': 'PERSON_INTERACTION'},
    68: {'name': 'hand shake', 'cls': 'PERSON_INTERACTION'},
    69: {'name': 'hand wave', 'cls': 'PERSON_INTERACTION'},
    70: {'name': 'hug (a person)', 'cls': 'PERSON_INTERACTION'},
    71: {'name': 'kick (a person)', 'cls': 'PERSON_INTERACTION'},
    72: {'name': 'kiss (a person)', 'cls': 'PERSON_INTERACTION'},
    73: {'name': 'lift (a person)', 'cls': 'PERSON_INTERACTION'},
    74: {'name': 'listen to (a person)', 'cls': 'PERSON_INTERACTION'},
    75: {'name': 'play with kids', 'cls': 'PERSON_INTERACTION'},
    76: {'name': 'push (another person)', 'cls': 'PERSON_INTERACTION'},
    77: {'name': 'sing to (e.g., self, a person, a group)', 'cls': 'PERSON_INTERACTION'},
    78: {'name': 'take (an object) from (a person)', 'cls': 'PERSON_INTERACTION'},
    79: {'name': 'talk to (e.g., self, a person, a group)', 'cls': 'PERSON_INTERACTION'},
    80: {'name': 'watch (a person)', 'cls': 'PERSON_INTERACTION'}
}

## Video files processing

For example, let's find all frames with "**write**" action (`action_id = 63`):

In [10]:
from datachain import C

write_frames_dc = annotations_dc.filter(C("action_id") == 63)

Preview:

In [11]:
write_frames_dc.show(10)

,video_id,timestamp,box_left,box_top,box_right,box_bottom,action_id,person_id
0,-OyDO1g74vc,1342,0.009,0.005,0.630,0.995,63,62
1,-OyDO1g74vc,1343,0.003,0.014,0.610,0.995,63,62
2,-OyDO1g74vc,1344,0.000,0.002,0.599,1.000,63,62
3,-OyDO1g74vc,1345,0.009,0.001,0.601,0.992,63,62
4,-OyDO1g74vc,1346,0.008,0.002,0.609,0.993,63,62
5,-OyDO1g74vc,1347,0.005,0.004,0.615,1.000,63,62
6,-OyDO1g74vc,1348,0.000,0.003,0.578,0.995,63,62
7,-OyDO1g74vc,1349,0.002,0.008,0.593,1.000,63,62
8,-OyDO1g74vc,1350,0.005,0.009,0.570,0.998,63,62
9,-OyDO1g74vc,1351,0.023,0.000,0.603,0.981,63,62

[Limited by 10 rows]

Build clips from these frames:

In [12]:
from typing import Iterator
from datachain import C, DataModel

class ClipInterval(DataModel):
    video_id: str
    person_id: int
    start: int
    end: int
    frames: int

def process(video_id, person_id, timestamp) -> Iterator[ClipInterval]:
    yield ClipInterval(
        video_id=video_id[0],
        person_id=person_id[0],
        start=timestamp[0],
        end=timestamp[-1],
        frames=len(video_id),
    )

clips_dc = write_frames_dc.order_by("video_id", "timestamp").agg(
    process,
    output=["clip"],
    partition_by=[C("video_id"), C("person_id")],
).filter(C("clip.frames") > 1).save()

Processed: 0 rows [00:00, ? rows/s]

Preview:

In [13]:
clips_dc.show(10)

          clip      clip  clip  clip   clip
      video_id person_id start   end frames
0  -OyDO1g74vc        62  1342  1357     14
1  -XpUuIgyUHE       288  1367  1369      3
2  2FIHxnZKg6A       100  1130  1131      2
3  2fwni_Kjf2M        45  1117  1118      2
4  3_VjIRdXVdM       275  1491  1493      3
5  4ZpjKfu6Cl8       161  1295  1302      4
6  4ZpjKfu6Cl8       169  1305  1306      2
7  4ZpjKfu6Cl8       173  1313  1314      2
8  5LrOQEt_XVM       299  1671  1679      5
9  5LrOQEt_XVM       306  1715  1732      8

[Limited by 10 rows]

And create video clips from these frames using `VideoClip` model:

In [14]:
repo_clip_dc = repo_dc2.merge(
    clips_dc,
    on="video_id",
    right_on="clip.video_id",
    inner=True
)

Preview:

In [15]:
repo_clip_dc.show(10)

,file,file,file,file,file,file,file,file,video_id,clip,clip,clip,clip,clip
,source,path,size,version,etag,is_latest,last_modified,location,,video_id,person_id,start,end,frames
0,file:///Users/vlad/work/iterative/datachain-ex...,C3qk4yAMANk.mkv,492664807,,0x1.6a6de12000000p+30,1,2018-03-04 04:38:32+00:00,None,C3qk4yAMANk,C3qk4yAMANk,149,1268,1270,3
1,file:///Users/vlad/work/iterative/datachain-ex...,8VZEwOCQ8bc.mkv,406988513,,0x1.6a6ce0f000000p+30,1,2018-03-04 00:05:16+00:00,None,8VZEwOCQ8bc,8VZEwOCQ8bc,169,1771,1775,5
2,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,cWYJHb25EVs,cWYJHb25EVs,250,1609,1642,9
3,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,cWYJHb25EVs,cWYJHb25EVs,265,1646,1650,5
4,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,cWYJHb25EVs,cWYJHb25EVs,267,1657,1658,2
5,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,cWYJHb25EVs,cWYJHb25EVs,271,1660,1663,4
6,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,cWYJHb25EVs,cWYJHb25EVs,305,1781,1783,3
7,file:///Users/vlad/work/iterative/datachain-ex...,_Ca3gOdOHxU.mp4,541907613,,0x1.6a6b678000000p+30,1,2018-03-03 17:22:40+00:00,None,_Ca3gOdOHxU,_Ca3gOdOHxU,492,1195,1199,5
8,file:///Users/vlad/work/iterative/datachain-ex...,_Ca3gOdOHxU.mp4,541907613,,0x1.6a6b678000000p+30,1,2018-03-03 17:22:40+00:00,None,_Ca3gOdOHxU,_Ca3gOdOHxU,496,1201,1202,2
9,file:///Users/vlad/work/iterative/datachain-ex...,4ZpjKfu6Cl8.mkv,1037398704,,0x1.6a6c7e9400000p+30,1,2018-03-03 22:20:21+00:00,None,4ZpjKfu6Cl8,4ZpjKfu6Cl8,161,1295,1302,4

[Limited by 10 rows]

In [16]:
from datachain.lib.file import VideoFile, VideoClip

def process_clip(file: VideoFile, clip: ClipInterval) -> Iterator[VideoClip]:
    yield VideoClip(
        **file.model_dump(),
        start=clip.start,
        end=clip.end,
    )

video_clip_dc = repo_clip_dc.gen(process_clip, output=["file"]).save()

Processed: 0 rows [00:00, ? rows/s]
Processed: 2 rows [00:00, 13.49 rows/s]
Processed: 4 rows [00:00, 16.03 rows/s]
Processed: 6 rows [00:00, 12.68 rows/s]
Processed: 8 rows [00:00,  8.30 rows/s]
Processed: 10 rows [00:01,  6.58 rows/s]
Processed: 12 rows [00:01,  5.41 rows/s]
Processed: 14 rows [00:01,  6.65 rows/s]
Processed: 17 rows [00:02,  7.94 rows/s]
Processed: 19 rows [00:02,  8.92 rows/s]
Processed: 21 rows [00:02,  9.93 rows/s]
Processed: 23 rows [00:02, 11.32 rows/s]
Processed: 25 rows [00:02, 10.29 rows/s]
Processed: 27 rows [00:03, 10.11 rows/s]
Processed: 31 rows [00:03, 12.57 rows/s]
Processed: 33 rows [00:03, 12.87 rows/s]
Processed: 35 rows [00:03, 10.06 rows/s]
Processed: 41 rows [00:03, 14.82 rows/s]
Processed: 48 rows [00:04, 20.84 rows/s]

Preview:

In [17]:
video_clip_dc.show(10)

,file,file,file,file,file,file,file,file,file,file
,source,path,size,version,etag,is_latest,last_modified,location,start,end
0,file:///Users/vlad/work/iterative/datachain-ex...,C3qk4yAMANk.mkv,492664807,,0x1.6a6de12000000p+30,1,2018-03-04 04:38:32+00:00,None,1268.0,1270.0
1,file:///Users/vlad/work/iterative/datachain-ex...,8VZEwOCQ8bc.mkv,406988513,,0x1.6a6ce0f000000p+30,1,2018-03-04 00:05:16+00:00,None,1771.0,1775.0
2,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,1609.0,1642.0
3,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,1646.0,1650.0
4,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,1657.0,1658.0
5,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,1660.0,1663.0
6,file:///Users/vlad/work/iterative/datachain-ex...,cWYJHb25EVs.mp4,307394571,,0x1.6a6e283c00000p+30,1,2018-03-04 05:54:23+00:00,None,1781.0,1783.0
7,file:///Users/vlad/work/iterative/datachain-ex...,_Ca3gOdOHxU.mp4,541907613,,0x1.6a6b678000000p+30,1,2018-03-03 17:22:40+00:00,None,1195.0,1199.0
8,file:///Users/vlad/work/iterative/datachain-ex...,_Ca3gOdOHxU.mp4,541907613,,0x1.6a6b678000000p+30,1,2018-03-03 17:22:40+00:00,None,1201.0,1202.0
9,file:///Users/vlad/work/iterative/datachain-ex...,4ZpjKfu6Cl8.mkv,1037398704,,0x1.6a6c7e9400000p+30,1,2018-03-03 22:20:21+00:00,None,1295.0,1302.0

[Limited by 10 rows]

Save video clips:

In [ ]:
import os
from datetime import datetime, timezone
from typing import Iterator
from datachain.lib.video import save_video_clip
from datachain.lib.file import VideoClip, VideoFile

def process(file: VideoClip) -> Iterator[VideoFile]:
    source = f"{os.path.dirname(file.source)}/clips"
    file_stem = file.get_file_stem()
    file_ext = file.get_file_ext()
    file_name = f"{file_stem}_{int(file.start)}_{int(file.end)}.{file_ext}"
    file_path = f"data/ava/clips/{file_name}"
    save_video_clip(file, file.start - 1, file.end + 1, file_path)
    stats = os.stat(file_path)
    yield VideoFile(
        source=source,
        path=file_name,
        size=stats.st_size,
        etag=stats.st_mtime.hex(),
        is_latest=True,
        last_modified=datetime.fromtimestamp(stats.st_mtime, tz=timezone.utc),
        location=None,
    )

clips_dc = video_clip_dc.limit(30).gen(process, output=["file"]).save()

Processed: 0 rows [00:00, ? rows/s]



Processed: 1 rows [00:00,  3.08 rows/s]                                                                                                         | 8/75 [00:38<05:20,  4.78s/it, now=None]



Processed: 1 rows [00:00,  3.07 rows/s]                                                                                                         | 8/75 [00:38<05:20,  4.78s/it, now=None]

Moviepy - Building video data/ava/clips/C3qk4yAMANk_1268_1270.mkv.
MoviePy - Writing audio in C3qk4yAMANk_1268_1270TEMP_MPY_wvf_snd.mp4

nk:   0%|                                                                                                                                            | 0/89 [00:00<?, ?it/s, now=None]




Processed: 1 rows [00:00,  2.11 rows/s]                                                                                                         | 8/75 [00:38<05:21,  4.80s/it, now=None]



Processed: 1 rows [00:00,  2.10 rows/s]                                                                                                         | 8/75 [00:38<05:21,  4.80s/it, now=None]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/C3qk4yAMANk_1268_1270.mkv

  0%|                                                                                                                                               | 0/120 [00:00<?, ?it/s, now=None]
 32%|██████████████████████████████████████████                                                                                           | 38/120 [00:00<00:00, 375.32it/s, now=None]
 63%|████████████████████████████████████████████████████████████████████████████████████▏                                                | 76/120 [00:00<00:00, 364.53it/s, now=None]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 113/120 [00:00<00:00, 358.09it/s, now=None]




Processed: 1 rows [00:00,  1.12 rows/s]                                                                                                         | 8/75 [00:38<05:25,  4.86s/it, now=None]



Processed: 1 rows [00:00,  1.11 rows/s]                                                                                                         | 8/75 [00:38<05:25,  4.86s/it, now=None]

Moviepy - Done !
Moviepy - video ready data/ava/clips/C3qk4yAMANk_1268_1270.mkv

Processed: 2 rows [00:00,  2.19 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:39<05:27,  4.89s/it, now=None]
Processed: 2 rows [00:01,  2.19 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:39<05:27,  4.89s/it, now=None]
Processed: 2 rows [00:01,  2.19 rows/s]

Moviepy - Building video data/ava/clips/8VZEwOCQ8bc_1771_1775.mkv.
MoviePy - Writing audio in 8VZEwOCQ8bc_1771_1775TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                           | 0/133 [00:00<?, ?it/s, now=None]


3%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 110/133 [00:00<00:00, 934.64it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:39<05:28,  4.91s/it, now=None]
Processed: 2 rows [00:01,  2.19 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:39<05:28,  4.91s/it, now=None]
Processed: 2 rows [00:01,  2.19 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/8VZEwOCQ8bc_1771_1775.mkv

                                                                                                                                              | 0/150 [00:00<?, ?it/s, now=None]


████████████████████████████████████████████████████████████████████████████▏                                                       | 87/150 [00:00<00:00, 843.55it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:39<05:30,  4.94s/it, now=None]
Processed: 2 rows [00:01,  2.19 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:39<05:31,  4.94s/it, now=None]
Processed: 2 rows [00:01,  2.19 rows/s]
Processed: 3 rows [00:01,  1.84 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/8VZEwOCQ8bc_1771_1775.mkv

%|██████████████▌                                                                                                                         | 8/75 [00:39<05:33,  4.98s/it, now=None]
Processed: 3 rows [00:01,  1.84 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:39<05:33,  4.98s/it, now=None]
Processed: 3 rows [00:01,  1.84 rows/s]

Moviepy - Building video data/ava/clips/cWYJHb25EVs_1609_1642.mp4.
MoviePy - Writing audio in cWYJHb25EVs_1609_1642TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                           | 0/772 [00:00<?, ?it/s, now=None]


4%|██████████████████▏                                                                                                             | 110/772 [00:00<00:00, 915.84it/s, now=None]


1%|███████████████████████████████████████████████████▍                                                                           | 313/772 [00:00<00:00, 1502.19it/s, now=None]


1%|█████████████████████████████████████████████████████████████████████████████████████████▊                                     | 546/772 [00:00<00:00, 1853.66it/s, now=None]


5%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 736/772 [00:00<00:00, 1865.00it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:40<05:37,  5.04s/it, now=None]
Processed: 3 rows [00:02,  1.84 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:40<05:37,  5.04s/it, now=None]
Processed: 3 rows [00:02,  1.84 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/cWYJHb25EVs_1609_1642.mp4

                                                                                                                                              | 0/875 [00:00<?, ?it/s, now=None]


██████▊                                                                                                                             | 51/875 [00:00<00:01, 509.03it/s, now=None]


███████████████████████▏                                                                                                           | 160/875 [00:00<00:00, 849.37it/s, now=None]


███████████████████████████████████████▋                                                                                           | 270/875 [00:00<00:00, 961.26it/s, now=None]


███████████████████████████████████████████████████████                                                                            | 372/875 [00:00<00:00, 984.05it/s, now=None]


███████████████████████████████████████████████████████████████████████                                                           | 481/875 [00:00<00:00, 1021.25it/s, now=None]


███████████████████████████████████████████████████████████████████████████████████████▏                                          | 589/875 [00:00<00:00, 1039.26it/s, now=None]


██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 720/875 [00:00<00:00, 1126.49it/s, now=None]


███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 833/875 [00:00<00:00, 1101.29it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:41<05:45,  5.16s/it, now=None]
Processed: 3 rows [00:03,  1.84 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:41<05:45,  5.16s/it, now=None]
Processed: 3 rows [00:03,  1.84 rows/s]
Processed: 4 rows [00:03,  1.02s/ rows]

Moviepy - Done !
Moviepy - video ready data/ava/clips/cWYJHb25EVs_1609_1642.mp4

%|██████████████▌                                                                                                                         | 8/75 [00:41<05:48,  5.21s/it, now=None]
Processed: 4 rows [00:03,  1.02s/ rows]




%|██████████████▌                                                                                                                         | 8/75 [00:41<05:48,  5.21s/it, now=None]
Processed: 4 rows [00:03,  1.02s/ rows]

Moviepy - Building video data/ava/clips/cWYJHb25EVs_1646_1650.mp4.
MoviePy - Writing audio in cWYJHb25EVs_1646_1650TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                           | 0/133 [00:00<?, ?it/s, now=None]


3%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 110/133 [00:00<00:00, 951.59it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:41<05:50,  5.23s/it, now=None]
Processed: 4 rows [00:03,  1.02s/ rows]




%|██████████████▌                                                                                                                         | 8/75 [00:41<05:50,  5.23s/it, now=None]
Processed: 4 rows [00:03,  1.02s/ rows]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/cWYJHb25EVs_1646_1650.mp4

                                                                                                                                              | 0/150 [00:00<?, ?it/s, now=None]


█████████████████████████████████████████████████████████████████████████████████████▉                                              | 98/150 [00:00<00:00, 975.96it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:42<05:52,  5.25s/it, now=None]
Processed: 4 rows [00:04,  1.02s/ rows]




%|██████████████▌                                                                                                                         | 8/75 [00:42<05:52,  5.25s/it, now=None]
Processed: 4 rows [00:04,  1.02s/ rows]
Processed: 5 rows [00:04,  1.10 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/cWYJHb25EVs_1646_1650.mp4

%|██████████████▌                                                                                                                         | 8/75 [00:42<05:54,  5.29s/it, now=None]
Processed: 5 rows [00:04,  1.10 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:42<05:54,  5.29s/it, now=None]
Processed: 5 rows [00:04,  1.10 rows/s]

Moviepy - Building video data/ava/clips/cWYJHb25EVs_1657_1658.mp4.
MoviePy - Writing audio in cWYJHb25EVs_1657_1658TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                            | 0/67 [00:00<?, ?it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:42<05:55,  5.31s/it, now=None]
Processed: 5 rows [00:04,  1.10 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:42<05:55,  5.31s/it, now=None]
Processed: 5 rows [00:04,  1.10 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/cWYJHb25EVs_1657_1658.mp4

                                                                                                                                               | 0/75 [00:00<?, ?it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:42<05:57,  5.33s/it, now=None]
Processed: 5 rows [00:04,  1.10 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:42<05:57,  5.33s/it, now=None]
Processed: 5 rows [00:04,  1.10 rows/s]
erated: 5 rows [00:03,  1.28 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/cWYJHb25EVs_1657_1658.mp4

Processed: 6 rows [00:04,  1.15 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:43<06:01,  5.39s/it, now=None]
Processed: 6 rows [00:05,  1.15 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:43<06:01,  5.39s/it, now=None]
Processed: 6 rows [00:05,  1.15 rows/s]

Moviepy - Building video data/ava/clips/cWYJHb25EVs_1660_1663.mp4.
MoviePy - Writing audio in cWYJHb25EVs_1660_1663TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                           | 0/111 [00:00<?, ?it/s, now=None]


0%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 850.99it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:43<06:02,  5.42s/it, now=None]
Processed: 6 rows [00:05,  1.15 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:43<06:02,  5.42s/it, now=None]
Processed: 6 rows [00:05,  1.15 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/cWYJHb25EVs_1660_1663.mp4

                                                                                                                                              | 0/125 [00:00<?, ?it/s, now=None]


████████████████████████████████████████████████████████████████████████████████████████████████████                                | 95/125 [00:00<00:00, 947.45it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:43<06:04,  5.44s/it, now=None]
Processed: 6 rows [00:05,  1.15 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:43<06:04,  5.44s/it, now=None]
Processed: 6 rows [00:05,  1.15 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/cWYJHb25EVs_1660_1663.mp4

Processed: 7 rows [00:05,  1.23 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:43<06:07,  5.48s/it, now=None]
Processed: 7 rows [00:05,  1.23 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:43<06:07,  5.48s/it, now=None]
Processed: 7 rows [00:05,  1.23 rows/s]

Moviepy - Building video data/ava/clips/cWYJHb25EVs_1781_1783.mp4.
MoviePy - Writing audio in cWYJHb25EVs_1781_1783TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                            | 0/89 [00:00<?, ?it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:44<06:08,  5.50s/it, now=None]
Processed: 7 rows [00:06,  1.23 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:44<06:08,  5.50s/it, now=None]
Processed: 7 rows [00:06,  1.23 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/cWYJHb25EVs_1781_1783.mp4

                                                                                                                                              | 0/100 [00:00<?, ?it/s, now=None]


█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 98/100 [00:00<00:00, 974.64it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:44<06:09,  5.52s/it, now=None]
Processed: 7 rows [00:06,  1.23 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:44<06:10,  5.52s/it, now=None]
Processed: 7 rows [00:06,  1.23 rows/s]
Processed: 8 rows [00:06,  1.31 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/cWYJHb25EVs_1781_1783.mp4

%|██████████████▌                                                                                                                         | 8/75 [00:44<06:12,  5.56s/it, now=None]
Processed: 8 rows [00:06,  1.31 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:44<06:12,  5.56s/it, now=None]
Processed: 8 rows [00:06,  1.31 rows/s]

Moviepy - Building video data/ava/clips/_Ca3gOdOHxU_1195_1199.mp4.
MoviePy - Writing audio in _Ca3gOdOHxU_1195_1199TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                           | 0/133 [00:00<?, ?it/s, now=None]


3%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 110/133 [00:00<00:00, 1010.23it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:44<06:13,  5.58s/it, now=None]
Processed: 8 rows [00:06,  1.31 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:44<06:13,  5.58s/it, now=None]
Processed: 8 rows [00:06,  1.31 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/_Ca3gOdOHxU_1195_1199.mp4

                                                                                                                                              | 0/150 [00:00<?, ?it/s, now=None]


█████████████████████████████████████████████████████████████████▌                                                                  | 75/150 [00:00<00:00, 729.81it/s, now=None]


█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 148/150 [00:00<00:00, 593.68it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:45<06:17,  5.63s/it, now=None]
Processed: 8 rows [00:07,  1.31 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:45<06:17,  5.63s/it, now=None]
Processed: 8 rows [00:07,  1.31 rows/s]
Processed: 9 rows [00:07,  1.25 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/_Ca3gOdOHxU_1195_1199.mp4

%|██████████████▌                                                                                                                         | 8/75 [00:45<06:20,  5.67s/it, now=None]
Processed: 9 rows [00:07,  1.25 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:45<06:20,  5.67s/it, now=None]
Processed: 9 rows [00:07,  1.25 rows/s]

Moviepy - Building video data/ava/clips/_Ca3gOdOHxU_1201_1202.mp4.
MoviePy - Writing audio in _Ca3gOdOHxU_1201_1202TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                            | 0/67 [00:00<?, ?it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:45<06:21,  5.69s/it, now=None]
Processed: 9 rows [00:07,  1.25 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:45<06:21,  5.69s/it, now=None]
Processed: 9 rows [00:07,  1.25 rows/s]

MoviePy - Done.
Moviepy - Writing video data/ava/clips/_Ca3gOdOHxU_1201_1202.mp4

                                                                                                                                               | 0/75 [00:00<?, ?it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:45<06:23,  5.72s/it, now=None]
Processed: 9 rows [00:07,  1.25 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:45<06:23,  5.72s/it, now=None]
Processed: 9 rows [00:07,  1.25 rows/s]
Processed: 10 rows [00:07,  1.23 rows/s]

Moviepy - Done !
Moviepy - video ready data/ava/clips/_Ca3gOdOHxU_1201_1202.mp4

%|██████████████▌                                                                                                                         | 8/75 [00:46<06:26,  5.77s/it, now=None]
Processed: 10 rows [00:08,  1.23 rows/s]




%|██████████████▌                                                                                                                         | 8/75 [00:46<06:26,  5.77s/it, now=None]
Processed: 10 rows [00:08,  1.23 rows/s]

Moviepy - Building video data/ava/clips/4ZpjKfu6Cl8_1295_1302.mkv.
MoviePy - Writing audio in 4ZpjKfu6Cl8_1295_1302TEMP_MPY_wvf_snd.mp4

0%|                                                                                                                                           | 0/199 [00:00<?, ?it/s, now=None]


5%|██████████████████████████████████████████████████████████████████████▊                                                         | 110/199 [00:00<00:00, 946.44it/s, now=None]







%|██████████████▌                                                                                                                         | 8/75 [00:46<06:28,  5.80s/it, now=None]
Processed: 10 rows [00:08,  1.23 rows/s]

MoviePy - Done.

%|██████████████▌                                                                                                                         | 8/75 [00:46<06:28,  5.80s/it, now=None]
Processed: 10 rows [00:08,  1.23 rows/s]

Moviepy - Writing video data/ava/clips/4ZpjKfu6Cl8_1295_1302.mkv

                                                                                                                                              | 0/270 [00:00<?, ?it/s, now=None]


████████████████████▋                                                                                                               | 44/270 [00:00<00:00, 439.12it/s, now=None]


██████████████████████████████████████████▎                                                                                         | 88/270 [00:00<00:00, 344.40it/s, now=None]

Preview:

In [ ]:
clips_dc.show(10)